#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done
unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	river="XKB_DEFAULT_LAYOUT=it river" \
	cp="cp -iv" \
	nnn="nnn -e" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rg="cd .steam/steam/steamapps/compatdata/813780/pfx/drive_c/users/steamuser/Games/Age\ of\ Empires\ 2\ DE/76561199050658286/savegame" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="exa --header --icons --group-directories-first" \
	cat="bat" \
	ll="exa --long --header --icons --color-scale --group-directories-first" \
	nn="cd ~/.config/nvim/lua/user/ && ls" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	mbsync="mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="nvim" \
	v="nvim" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	config="/usr/bin/git --git-dir=/home/soliprem/.cfg/ --work-tree=/home/soliprem" \
	z="zathura"

alias \
	cd..="cd .." \
	lf="lfub" \
	vifm="vifmrun" \
	yay="paru" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"
